### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by toddmotto** [html5blank/html5blank#125]
Hey all, so I hashed together the HTML5blank website a long long time ago. I think it sucks. Any thoughts on redeveloping it and design ideas? It gets an absolute tonne of traffic so would be awesome to give people something decent to look at.

**Comment by oriSomething** [comment]
it's not sucks. it needs only some small fixes. but as i got to learn you, i guess you just want newish and shinier design :)

but if i think we should remove the "nightly" and "stable" links for direct download to master.

**Comment by LeoFNaN** [comment]
Alright, I ask more questions then getting to somewhere concrete :)

I like the current color scheme (or minimal color scheme) I say keep it if you planned on changing the scheme, keep its "branding".  Do you have a general idea of the layout or a prototype? and I'm assuming responsiveness will be implicit?

For the demo section I thought of probably adding a showcase of really simple and basic layouts using the theme to display what's possible.  As long as it's communicated that the theme doesn't come with these layouts these are just for "inspiration" or have the css available separately to include in the project

I agree with oris suggestion of removing nightly and stable links from the home page, but I suggest create a page specifically for developers where those links can be available and iterating the features that are on the main page of the repo and displaying outstanding issues?

and one more thing :) I like the idea of having comments on the homepage but maybe less dominant it gives the feeling that the website is "lively"

**Comment by toddmotto** [comment]
@LeoFNaN Great comment! I think it needs to showcase what WordPress sites are also running on HTML5 blank, some top mega websites I found were these: Elton John, Damien Rice, George Michael, Mark Knopflers official websites and Seattle needle.

**Comment by itsduc** [comment]
That sounds great. I can help with this! Does anyone have a design ideas? I agree on it being simple as well.

**Comment by toddmotto** [comment]
What do you think to the colour scheme of something like this @itsduc and all? Specifically the code examples as you scroll down: https://dev.fedger.io/docs/

**Comment by pothi** [comment]
When you re-design the main site, please consider updating the [demo site](http://demo.html5blank.com/) as well with more [sample data](https://codex.wordpress.org/Theme_Unit_Test#Test_Environment_Setup). At least, please update it to the latest version of WordPress core. You have already done a great work. Thank you!

**Comment by pgerochi** [comment]
closing this, you can go to http://html5blank.com/
