### ISSUE TITLE
demo site is down

### ISSUE THREAD

**Issue by scottaohara** [html5blank/html5blank#158]
[the html5blank demo site](http://demo.html5blank.com/) currently resolves to:
"Error establishing a database connection"

**Comment by oriSomething** [comment]
@toddmotto ?

**Comment by mandazi** [comment]
Demo site still down.

**Comment by eristavi** [comment]
Still no changes to demo site?

**Comment by MediaMaquina** [comment]
Any news on the demo? I wouldn't really waste time installing a theme that won't bother to put up a functional demo.
