### ISSUE TITLE
A farewell from me!

### ISSUE THREAD

**Issue by toddmotto** [html5blank/html5blank#179]
Hey everyone, just wanted to give you a heads up that @deviodigital is now taking the lead on this project and we're in the process of transferring the gauntlet to his safe hands. He's a very fine master of WordPress and I'm excited to see where he takes this project for the community.

A while ago I switched to writing Angular every day, and as a result I now run [Ultimate Angular](https://ultimateangular.com) where I teach it full-time, so my focus has steered away from WordPress and it really needs to live with someone that can contribute much more than I can nowadays.

HTML5Blank was my first ever open source project so I'm sad to "see it go", but I'd rather the community benefit broadly from Robert's expertise. The project got very popular very quickly and is still being used by thousands of WordPress developers each month, so a huge thanks from me for the inspiration to continue open source work (and to everyone that's used the theme!).

To date, the website html5blank.com has over 500 community comments, 630,161 unique visits and 826,382 page views, sadly I don't have any statistics on the download count, but it powers some mighty fine websites such as Elton John's and some ESPN sites.

It's been a really fun ride creating this theme years ago and it's gone so far! All the best to everyone using it now and in future :)

Happy coding,
Todd <3

**Comment by deviodigital** [comment]
Thanks for the opportunity to continue moving the html5blank theme forward 🙌

Happy to be a part of it's journey and I hope to make you proud of where your first open source project goes from here 💪💯

**Comment by toddmotto** [comment]
Good luck sir! I know you'll rock it 💃
