### ISSUE TITLE
Sidebar only shows on the bottom of the page

### ISSUE THREAD

**Issue by JumanjiCraft** [html5blank/html5blank#183]
I can't figure out why but no matter what I try, the sidebar appears below the content of my site. I tried checking for unclosed <div> elements, I tried checking the sidebar.php and page.php. I also changed element widths with CSS, and it would still appear on the bottom. 

http://www.musicfactory.tm/test

**Comment by pgerochi** [comment]
Hey @JumanjiCraft - it's a bit unrelated to html5blank but I hope this helps you. Try: 
`main {
    display: inline-block;
}

sidebar {
   float: right;
}`

Hope that works.

**Comment by gfrow** [comment]
I'm having the same issue.

**Comment by vinie11** [comment]
Hello
I only see my sidebar in the footer.
I want to move my sidebar to my body.
does anyone have an idea how to do that.
