### ISSUE TITLE
Nav menu

### ISSUE THREAD

**Issue by gfrow** [html5blank/html5blank#188]
How do I style the header menu? I Want a horizontal menu and for the life of me I can't figure it out.

**Comment by pgerochi** [comment]
Hey @gfrow there are currently just basic styles and no styling for the header menu as we tried to keep it as basic as possible hence html5blank. If you are looking for a framework to use in order to style the header, i suggest installing something like https://getbootstrap.com/

**Comment by gfrow** [comment]
Right, I'm added wp_enqueue for bootstrap and tried to style with that but it won't come out of the vertical layout... I've added .navmenu li {display: inline; } and still nothing. I'm stumped.

**Comment by gfrow** [comment]
It's probably something crazy simple but I have not, after 3 weeks of building with html5blank been able to do this.

**Comment by pgerochi** [comment]
can you send me the link? I can help you take a look at it

**Comment by ekntrtmz** [comment]
Have a look at these bootstrap examples. Maybe you can dig it
https://getbootstrap.com/docs/4.0/examples/navbars/

**Comment by gfrow** [comment]
pgerochi, It's on my local machine. Do you perhaps just have a sample of a menu and how and where you styled it to be horizontal? I think I'm probably just missing something really super simple as I've done this several times before and not had a problem.

**Comment by gfrow** [comment]
ekntrtmz, Thank you. I have bootstrap.css setup and enqueued in the functions.php and it works great for all other elements. I just cannot figure out where to style the nav. I think there may be some kind of filter or something that I'm not seeing.

**Comment by kvanderelst** [comment]
Hello. Did you tell Wordpress to use your menu in the Header ? On your menu page you have to check the first checkbox on the "Display location" option.

**Comment by toddkc** [comment]
I could be way off here, but isn't the issue that wordpress is generating the menu html, and it doesn't add in the classes that bootstrap looks for (like nav-item)?  I think if you want to use bootstrap you have to make your own menu, not use the wordpress generated one.

**Comment by ekntrtmz** [comment]
@gfrow You can use this https://github.com/dupkey/bs4navwalker

**Comment by gfrow** [comment]
So my menu is showing up like: 

Category
      item
      item
Category
      item 
      item
     item...

Instead of horizontally. I see the php for the nav in the header.php, but I still cannot freaking get it to work. What am I missing?

**Comment by yeltsinseal** [comment]
Just a tip. If your goal is to integrate with Bootstrap, is better to use a starter theme with bootstrap included. See understrap: https://understrap.com/ // https://github.com/understrap/understrap :)

**Comment by robertdevore** [comment]
@gfrow, If you still are having issues with this, please re-open a new issue and provide a link to the current set up so I can look it over and provide some more insight for you.

@yeltsinseal Once version 2.0 of HTML5Blank is built, I'll be creating some child themes as starters for people to use their favorite framework - including Bootstrap :+1:
