### ISSUE TITLE
HTML5 Blank Custom Post-Type

### ISSUE THREAD

**Issue by iKova82** [html5blank/html5blank#194]
Hello,

i startet using this theme.
I understand all these code snippets and functions in this template except 1 thing.

What is "HTML5 Blank Custom Post-Type"? What it does? There are no infos about that.
And can i disabled it?

Hope you can help :)
Thanks! #

**Comment by robertdevore** [comment]
The HTML5Blank custom post type is added on [this line](https://github.com/html5blank/html5blank/blob/master/src/functions.php#L370) of the functions.php file.

You can remove that line to remove the CPT from being added.

If you want to keep the CPT but change things up with it, you can do that on [these lines](https://github.com/html5blank/html5blank/blob/master/src/functions.php#L412-L451)
