### ISSUE TITLE
thumnail size.

### ISSUE THREAD

**Issue by helvetica123** [html5blank/html5blank#197]
i cant resize thumnail size. i use this code on index.php

` <?php if ( has_post_thumbnail() ) {   
the_post_thumbnail('entry',  array('class' => 'img-responsive') );
} else { ?>
<img src="<?php bloginfo('template_directory'); ?>/images/default-image.jpg" alt="Avatar"class="image"  />`

in the fuctions.php contains that code:

`add_image_size('entry', 100, 490, true);

    // Add Thumbnail Theme Support
    add_theme_support('post-thumbnails');
    add_image_size('large', 700, '', true); // Large Thumbnail
    add_image_size('medium', 250, '', true); // Medium Thumbnail
    add_image_size('small', 120, '', true); // Small Thumbnai
    add_image_size('custom-size', 700, 200, true); // Custom Thumbnail Size call using the_post_thumbnail('custom-size');`

i tried to change that size values but there was not any changes.can you help me?

**Comment by robertdevore** [comment]
After you change thumbnail sizes, images that have already been cropped at the previous sizes will need to be regenerated.

You can use the [Regeneration plugin](https://wordpress.org/plugins/regenerate-thumbnails/) to automatically recrop all images at the new size(s).
